In [1]:
library("clusterProfiler")

clusterProfiler v4.16.0 Learn more at https://yulab-smu.top/contribution-knowledge-mining/

Please cite:

T Wu, E Hu, S Xu, M Chen, P Guo, Z Dai, T Feng, L Zhou, W Tang, L Zhan,
X Fu, S Liu, X Bo, and G Yu. clusterProfiler 4.0: A universal
enrichment tool for interpreting omics data. The Innovation. 2021,
2(3):100141


Attaching package: ‘clusterProfiler’


The following object is masked from ‘package:stats’:

    filter

In [2]:
library("org.Hs.eg.db")

Loading required package: AnnotationDbi

Loading required package: stats4

Loading required package: BiocGenerics

Loading required package: generics


Attaching package: ‘generics’


The following objects are masked from ‘package:base’:

    as.difftime, as.factor, as.ordered, intersect, is.element, setdiff,
    setequal, union



Attaching package: ‘BiocGenerics’


The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs


The following objects are masked from ‘package:base’:

    anyDuplicated, aperm, append, as.data.frame, basename, cbind,
    colnames, dirname, do.call, duplicated, eval, evalq, Filter, Find,
    get, grep, grepl, is.unsorted, lapply, Map, mapply, match, mget,
    order, paste, pmax, pmax.int, pmin, pmin.int, Position, rank,
    rbind, Reduce, rownames, sapply, saveRDS, table, tapply, unique,
    unsplit, which.max, which.min


Loading required package: Biobase

Welcome to Bioconductor

    Vignettes contain introductory material; view with
    'browseVignettes()'. To cite Bioconductor, see
    'citation("Biobase")', and for packages 'citation("pkgname")'.


Loading required package: IRanges

Loading required package: S4Vectors


Attaching package: ‘S4Vectors’


The following object is masked from ‘package:clusterProfiler’:

    rename


The following object is masked from ‘package:utils’:

    findMatches


The following objects are masked from ‘package:base’:

    expand.grid, I, unname



Attaching package: ‘IRanges’


The following object is masked from ‘package:clusterProfiler’:

    slice



Attaching package: ‘AnnotationDbi’


The following object is masked from ‘package:clusterProfiler’:

    select

In [3]:
gseKegg <- function(sorted_genes) { # `genes` has to be sorted
    hs <- org.Hs.eg.db
    my.symbols <- names(sorted_genes)
    g <- AnnotationDbi::select(hs, keys = my.symbols, columns = c("ENTREZID", "SYMBOL", "ENSEMBL"), keytype = "ENSEMBL")
    g <- g[!is.na(g$ENTREZID),]
    g <- g[!duplicated(g$ENSEMBL),]
    sorted_genes <- sorted_genes[names(sorted_genes) %in% g$ENSEMBL]
    names(sorted_genes) <- g$ENTREZID
    res <- gseKEGG(sorted_genes, organism = "hsa", keyType = "kegg", pvalueCutoff = 1)
    
    return(res)
}

gseGo <- function(sorted_genes) { # `genes` has to be sorted
    res <- gseGO(sorted_genes, OrgDb=org.Hs.eg.db, ont = "BP", pvalueCutoff = 1, keyType = "ENSEMBL")
    return(res)
}

genes <- read.table("/scratch/scjp_root/scjp1/christav/fap_village_multiome/results/mast/all.fcHurdle.final.txt", header = T)
genes$ID <- sub("\\..*", "", rownames(genes))

tmp <- genes[!is.na(genes$fdr),]
tmp <- tmp[order(tmp$log2FC, decreasing = T),]
genelist <- tmp$log2FC
names(genelist) <- tmp$ID
gsea_go <- gseGo(genelist)

gsea_kegg <- gseKegg(genelist)

using 'fgsea' for GSEA analysis, please cite Korotkevich et al (2019).


preparing geneSet collections...

GSEA analysis...

Warning message in fgseaMultilevel(pathways = pathways, stats = stats, minSize = minSize, :
“For some of the pathways the P-values were likely overestimated. For such pathways log2err is set to NA.”
Warning message in fgseaMultilevel(pathways = pathways, stats = stats, minSize = minSize, :
“For some pathways, in reality P-values are less than 1e-10. You can set the `eps` argument to zero for better estimation.”
leading edge analysis...

done...

'select()' returned 1:many mapping between keys and columns

Reading KEGG annotation online: "https://rest.kegg.jp/link/hsa/pathway"...

Reading KEGG annotation online: "https://rest.kegg.jp/list/pathway/hsa"...

using 'fgsea' for GSEA analysis, please cite Korotkevich et al (2019).


preparing geneSet collections...

GSEA analysis...

Warning message in fgseaMultilevel(pathways = pathways, stats = stats, minSize = minSize, :
“For some of the pathways the P-values were likely overestimated. For such pathways log2err is set to NA.”
Warning message in fgseaMultilevel(pathways = pathways, stats = stats, minSize = minSize, :
“For some pathways, in reality P-values are less than 1e-10. You can set the `eps` argument to zero for better estimation.”
leading edge analysis...

done...

In [4]:
head(gsea_go)
write.table(gsea_go, "gsea_go.final.txt", sep = "\t", col.names = TRUE, row.names = FALSE, quote = FALSE)

           ID         Description
GO:0002181 GO:0002181 cytoplasmic translation
GO:0051056 GO:0051056 regulation of small GTPase mediated signal transduction
GO:0000902 GO:0000902 cell morphogenesis
GO:0007423 GO:0007423 sensory organ development
GO:0048858 GO:0048858 cell projection morphogenesis
GO:0120039 GO:0120039 plasma membrane bounded cell projection morphogenesis
           setSize enrichmentScore NES       pvalue p.adjust     qvalue
GO:0002181 152     -0.8274500      -2.330391 1e-10  1.633333e-08 1.272904e-08
GO:0051056 165      0.6437331       2.196372 1e-10  1.633333e-08 1.272904e-08
GO:0000902 496      0.5947166       2.185324 1e-10  1.633333e-08 1.272904e-08
GO:0007423 230      0.5960882       2.073099 1e-10  1.633333e-08 1.272904e-08
GO:0048858 333      0.5706733       2.053761 1e-10  1.633333e-08 1.272904e-08
GO:0120039 330      0.5671821       2.037814 1e-10  1.633333e-08 1.272904e-08
           rank leading_edge
GO:0002181  503 tags=56%, list=6%, signal=53%
GO:0051056 1198 tags=28%, list=15%, signal=25%
GO:0000902 1021 tags=28%, list=13%, signal=26%
GO:0007423  936 tags=29%, list=12%, signal=27%
GO:0048858 1213 tags=29%, list=15%, signal=26%
GO:0120039 1213 tags=29%, list=15%, signal=26%
           core_enrichment
GO:0002181 ENSG00000111361/ENSG00000163584/ENSG00000198034/ENSG00000100316/ENSG00000143486/ENSG00000065978/ENSG00000204628/ENSG00000149273/ENSG00000089009/ENSG00000142676/ENSG00000170889/ENSG00000174444/ENSG00000122406/ENSG00000198755/ENSG00000265681/ENSG00000174748/ENSG00000168028/ENSG00000161016/ENSG00000188846/ENSG00000148303/ENSG00000089157/ENSG00000232119/ENSG00000115268/ENSG00000149806/ENSG00000147604/ENSG00000142541/ENSG00000140988/ENSG00000171863/ENSG00000063177/ENSG00000116251/ENSG00000156482/ENSG00000137154/ENSG00000138326/ENSG00000145425/ENSG00000167526/ENSG00000136942/ENSG00000109475/ENSG00000142937/ENSG00000114391/ENSG00000231500/ENSG00000142534/ENSG00000108107/ENSG00000105640/ENSG00000177954/ENSG00000172809/ENSG00000131469/ENSG00000143947/ENSG00000147403/ENSG00000108298/ENSG00000083845/ENSG00000008988/ENSG00000233927/ENSG00000241343/ENSG00000166441/ENSG00000125691/ENSG00000105372/ENSG00000197958/ENSG00000163682/ENSG00000197756/ENSG00000221983/ENSG00000105193/ENSG00000122026/ENSG00000164587/ENSG00000118181/ENSG00000110700/ENSG00000137818/ENSG00000162244/ENSG00000161970/ENSG00000124614/ENSG00000177600/ENSG00000130255/ENSG00000144713/ENSG00000186468/ENSG00000071082/ENSG00000182899/ENSG00000198918/ENSG00000145592/ENSG00000171858/ENSG00000213741/ENSG00000197728/ENSG00000134419/ENSG00000229117/ENSG00000198242/ENSG00000182774/ENSG00000112306
GO:0051056 ENSG00000073712/ENSG00000116641/ENSG00000170776/ENSG00000038382/ENSG00000196914/ENSG00000110395/ENSG00000185989/ENSG00000138448/ENSG00000214944/ENSG00000071205/ENSG00000133789/ENSG00000164741/ENSG00000140750/ENSG00000173706/ENSG00000073921/ENSG00000143322/ENSG00000135905/ENSG00000197555/ENSG00000107554/ENSG00000275832/ENSG00000049130/ENSG00000099331/ENSG00000150093/ENSG00000145147/ENSG00000196712/ENSG00000132155/ENSG00000107863/ENSG00000136205/ENSG00000088387/ENSG00000159842/ENSG00000071054/ENSG00000168542/ENSG00000187678/ENSG00000110906/ENSG00000175220/ENSG00000105738/ENSG00000134250/ENSG00000133121/ENSG00000160007/ENSG00000133703/ENSG00000119487/ENSG00000039523/ENSG00000161011/ENSG00000005884/ENSG00000101199/ENSG00000139132/ENSG00000105339
GO:0000902 ENSG00000078401/ENSG00000058272/ENSG00000067900/ENSG00000073712/ENSG00000169641/ENSG00000116641/ENSG00000132842/ENSG00000038382/ENSG00000049759/ENSG00000074047/ENSG00000170558/ENSG00000008294/ENSG00000148468/ENSG00000129116/ENSG00000162614/ENSG00000154380/ENSG00000163110/ENSG00000061676/ENSG00000204217/ENSG00000169398/ENSG00000165323/ENSG00000150457/ENSG00000197969/ENSG00000140945/ENSG00000100266/ENSG00000182197/ENSG00000149177/ENSG00000035403/ENSG00000140443/ENSG00000167657/ENSG00000127603/ENSG00000138814/ENSG00000214944/ENSG00000007168/ENSG00000174953/ENSG00000163697/ENSG00000137693/ENSG00000171456/ENSG00000140937/ENSG00000114062/ENSG00000162458/ENSG00000173706/ENSG00000073921/ENSG00000075711/ENSG00000135905/ENSG00000197555/ENSG00000084093/ENSG00000145555/ENSG00000107554/ENSG00000083857/ENSG00000101109/ENSG00000172037/ENSG00000158470/ENSG00000176697/ENSG00000131711/ENSG00000100345/ENSG00000110880/ENSG00000179242/ENSG00000161813/ENSG00000140416/ENSG00000169504/ENSG00000197702/ENSG00000139926/ENSG00000021645/ENSG00000136603/ENSG00000099331/ENSG00000163785/ENSG00000075539/ENSG00000144791/ENSG00000072110/ENSG00000150093/ENSG00000170017/ENSG00000145147/ENSG00000145715/ENSG00000142192/ENSG00000149571/ENSG00000130559/ENSG00000113140/ENSG00000147065/ENSG00000136068/ENSG00000069869/ENSG00000075223/ENSG00000166923/ENSG00000141380/ENSG00000133026/ENSG00000172260/ENSG00000122545/ENSG00000114315/ENSG00000166963/ENSG00000152767/ENSG00000137055/ENSG00000112655/ENSG00000138443/ENSG00000146247/ENSG00000124486/ENSG00000101126/ENSG00000071054/ENSG00000078618/ENSG00000176438/ENSG00000114251/ENSG00000146648/ENSG00000114019/ENSG00000125266/ENSG00000168621/ENSG00000120885/ENSG00000140575/ENSG00000079805/ENSG00000142279/ENSG00000147010/ENSG00000105738/ENSG00000182149/ENSG00000132688/ENSG00000026508/ENSG00000131236/ENSG00000253729/ENSG00000134250/ENSG00000106571/ENSG00000112902/ENSG00000163539/ENSG00000157827/ENSG00000166483/ENSG00000131504/ENSG00000169760/ENSG00000142627/ENSG00000125503/ENSG00000160007/ENSG00000072518/ENSG00000147439/ENSG00000138182/ENSG00000084234/ENSG00000180370/ENSG00000156642/ENSG00000158195/ENSG00000117298/ENSG00000142156/ENSG00000178209/ENSG00000196504
GO:0007423 ENSG00000078401/ENSG00000164190/ENSG00000187498/ENSG00000204217/ENSG00000137845/ENSG00000165323/ENSG00000138685/ENSG00000122641/ENSG00000033867/ENSG00000007168/ENSG00000130635/ENSG00000112893/ENSG00000166068/ENSG00000166147/ENSG00000075711/ENSG00000084093/ENSG00000083857/ENSG00000172037/ENSG00000143995/ENSG00000166949/ENSG00000157933/ENSG00000130508/ENSG00000088930/ENSG00000169504/ENSG00000136603/ENSG00000196712/ENSG00000177707/ENSG00000204262/ENSG00000113140/ENSG00000181027/ENSG00000139734/ENSG00000137936/ENSG00000081923/ENSG00000196586/ENSG00000144810/ENSG00000128791/ENSG00000151012/ENSG00000114315/ENSG00000112655/ENSG00000138443/ENSG00000073711/ENSG00000064393/ENSG00000168214/ENSG00000111186/ENSG00000106799/ENSG00000114251/ENSG00000124766/ENSG00000146648/ENSG00000174705/ENSG00000101596/ENSG00000138829/ENSG00000164930/ENSG00000100644/ENSG00000105738/ENSG00000187676/ENSG00000132688/ENSG00000204138/ENSG00000134250/ENSG00000106571/ENSG00000058668/ENSG00000173068/ENSG00000167081/ENSG00000142627/ENSG00000146555/ENSG00000172845/ENSG00000160007/ENSG00000118217
GO:0048858 ENSG00000078401/ENSG00000058272/ENSG00000067900/ENSG00000116641/ENSG00000038382/ENSG00000049759/ENSG00000074047/ENSG00000008294/ENSG00000129116/ENSG00000162614/ENSG00000154380/ENSG00000163110/ENSG00000061676/ENSG00000204217/ENSG00000169398/ENSG00000197969/ENSG00000100266/ENSG00000182197/ENSG00000149177/ENSG00000035403/ENSG00000140443/ENSG00000127603/ENSG00000138814/ENSG00000214944/ENSG00000007168/ENSG00000174953/ENSG00000163697/ENSG00000140937/ENSG00000114062/ENSG00000073921/ENSG00000135905/ENSG00000197555/ENSG00000172037/ENSG00000158470/ENSG00000176697/ENSG00000131711/ENSG00000110880/ENSG00000179242/ENSG00000021645/ENSG00000136603/ENSG00000099331/ENSG00000163785/ENSG00000150093/ENSG00000170017/ENSG00000145147/ENSG00000142192/ENSG00000149571/ENSG00000069869/ENSG00000075223/ENSG00000172260/ENSG00000166963/ENSG00000152767/ENSG00000137055/ENSG00000112655/ENSG00000138443/ENSG00000124486/ENSG00000101126/ENSG00000071054/ENSG00000078618/ENSG00000114251/ENSG00000146648/ENSG00000125266/ENSG00000168621/ENSG00000140575/ENSG00000079805/ENSG00000182149/ENSG00000132688/ENSG00000026508/ENSG00000134250/ENSG00000106571/ENSG00000112902/ENSG00000163539/ENSG00000166483/ENSG00000169760/ENSG00000125503/ENSG00000160007/ENSG00000072518/ENSG00000138182/ENSG00000084234/ENSG00000180370/ENSG00000156642/ENSG00000158195/ENSG00000117298/ENSG00000197381/ENSG00000170385/ENSG00000067715/ENSG00000135298/ENSG00000159217/ENSG00000169032/ENSG00000114999/ENSG00000149294/ENSG00000196576/ENSG00000142599/ENSG00000113758/ENSG00000138623/ENSG00000066084/ENSG00000118257/ENSG00000171055
GO:0120039 ENSG00000078401/ENSG00000058272/ENSG00000067900/ENSG00000116641/ENSG00000038382/ENSG00000049759/ENSG00000074047/ENSG00000008294/ENSG00000129116/ENSG00000162614/ENSG00000154380/ENSG00000163110/ENSG00000061676/ENSG00000204217/ENSG00000169398/ENSG00000197969/ENSG00000182197/ENSG00000149177/ENSG00000035403/ENSG00000140443/ENSG00000127603/ENSG00000138814/ENSG00000214944/ENSG00000007168/ENSG00000174953/ENSG00000163697/ENSG00000140937/ENSG00000114062/ENSG00000073921/ENSG00000135905/ENSG00000197555/ENSG00000172037/ENSG00000158470/ENSG00000176697/ENSG00000131711/ENSG00000110880/ENSG00000179242/ENSG00000021645/ENSG00000136603/ENSG00000099331/ENSG00000163785/ENSG00000150093/ENSG00000170017/ENSG00000145147/ENSG00000142192/ENSG00000149571/ENSG00000069869/ENSG00000075223/ENSG00000172260/ENSG00000166963/ENSG00000152767/ENSG00000137055/ENSG00000112655/ENSG00000138443/ENSG00000124486/ENSG00000101126/ENSG00000071054/ENSG00000078618/ENSG00000114251/ENSG00000146648/ENSG00000125266/ENSG00000168621/ENSG00000140575/ENSG00000079805/ENSG00000182149/ENSG00000026508/ENSG00000134250/ENSG00000106571/ENSG00000112902/ENSG00000163539/ENSG00000166483/ENSG00000169760/ENSG00000125503/ENSG00000160007/ENSG00000072518/ENSG00000138182/ENSG00000084234/ENSG00000180370/ENSG00000156642/ENSG00000158195/ENSG00000117298/ENSG00000197381/ENSG00000170385/ENSG00000067715/ENSG00000135298/ENSG00000159217/ENSG00000169032/ENSG00000114999/ENSG00000149294/ENSG00000196576/ENSG00000142599/ENSG00000113758/ENSG00000138623/ENSG00000066084/ENSG00000118257/ENSG00000171055

In [5]:
head(gsea_kegg)
write.table(gsea_kegg, "gsea_kegg.final.txt", sep = "\t", col.names = TRUE, row.names = FALSE, quote = FALSE)

         ID       Description                    setSize enrichmentScore
hsa05171 hsa05171 Coronavirus disease - COVID-19 130     -0.8528736
hsa03010 hsa03010 Ribosome                       125     -0.8476799
hsa05012 hsa05012 Parkinson disease              203     -0.6315671
hsa05016 hsa05016 Huntington disease             226     -0.6191657
hsa05020 hsa05020 Prion disease                  192     -0.6130218
hsa00190 hsa00190 Oxidative phosphorylation      111     -0.6831560
         NES       pvalue       p.adjust     qvalue       rank
hsa05171 -2.370684 1.000000e-10 1.510000e-08 1.215789e-08  626
hsa03010 -2.350818 1.000000e-10 1.510000e-08 1.215789e-08  496
hsa05012 -1.828512 6.521173e-10 4.923486e-08 3.964187e-08 1616
hsa05016 -1.806816 5.565399e-10 4.923486e-08 3.964187e-08 1616
hsa05020 -1.769786 1.223409e-08 7.389389e-07 5.949630e-07 1616
hsa00190 -1.877605 1.918528e-08 9.656589e-07 7.775085e-07 1316
         leading_edge
hsa05171 tags=66%, list=8%, signal=62%
hsa03010 tags=74%, list=6%, signal=70%
hsa05012 tags=55%, list=20%, signal=45%
hsa05016 tags=50%, list=20%, signal=41%
hsa05020 tags=53%, list=20%, signal=43%
hsa00190 tags=68%, list=17%, signal=57%
         core_enrichment
hsa05171 6192/5970/3661/51187/200916/6191/6122/6188/6128/6166/51065/6135/6203/6124/6125/4736/6139/6138/3921/6132/9045/6130/6175/6209/2197/6129/23521/6187/6201/6141/6146/6156/6194/6229/6189/6137/11224/6164/6202/6152/6222/6205/6158/6142/6232/6169/6155/6233/6134/6143/6193/6224/6234/6173/6157/9349/6223/6136/6133/6168/7311/6217/6144/6208/6230/6207/6176/6159/6154/6204/6181/25873/6161/6228/6160/6165/6170/6167/6227/6235/6231/6210/6171/6147/6218/6206
hsa03010 51187/200916/6191/6122/55173/64981/51069/6188/6128/64960/6166/51065/6135/6203/6124/6125/4736/64963/6139/6138/3921/6132/9045/6130/6175/6209/2197/54948/6129/23521/6187/6201/6141/6146/6156/51023/6194/6229/6189/6137/11224/6164/6202/6152/6222/6205/6158/6142/6232/6169/6155/6233/6134/6143/6193/6224/6234/6173/6157/9349/6223/6136/6133/6168/7311/6217/6144/6208/6230/6207/6176/63931/6159/6154/6204/6181/25873/6161/6228/6160/6165/6170/6167/6227/6235/6231/6210/6171/6147/6218/6206/28998
hsa05012 7416/11047/10381/4722/5715/7419/515/5705/808/5684/7417/27173/374291/7345/118424/54539/5690/581/5685/4696/7385/5714/4714/4698/51079/5682/2773/4728/1537/506/10476/4694/5689/6647/5686/5691/4712/4731/7386/513/55967/7332/4702/4700/5692/4706/203068/1329/9377/4713/539/4708/5683/10383/5694/2778/4717/5693/509/6390/126328/292/4718/4716/1616/4715/54205/4726/9167/1327/6392/801/4729/6391/516/11315/84790/522/293/1345/29985/10376/4709/4710/7314/1349/7979/29796/7295/1340/4711/4697/1337/5688/4695/4725/517/27089/10975/518/805/291/7381/7388/1350/1351/1347/514/6233/7311/4707/4701
hsa05016 7416/11047/10381/4722/5715/7419/515/5705/5684/7417/374291/1211/5434/54539/5690/581/10671/5685/11258/4696/7385/5436/5714/4714/4698/51079/5682/4728/1537/506/5331/10476/4694/5440/5689/6647/5686/5691/5439/4712/5435/4731/7386/513/55967/1173/4702/4700/5692/4706/203068/1329/9377/4713/539/4708/5683/10383/5694/4717/5693/509/6390/126328/292/4718/4716/4715/54205/4726/9167/1327/6392/4729/6391/516/84790/522/293/1345/10376/4709/4710/5438/2876/1349/7979/29796/1175/1340/4711/4697/1337/5688/4695/4725/517/27089/10975/518/291/7381/7388/5432/5437/1350/1351/60673/1347/514/5441/5433/4707/4701
hsa05020 7416/11047/10381/4722/5715/7419/515/5705/572/5684/7417/374291/54539/5690/581/5685/4696/7385/5714/4714/4698/51079/5682/4728/1537/506/10476/4694/1460/5689/6647/5686/5691/4712/4731/7386/513/55967/4702/4700/5692/857/4706/203068/1329/9377/4713/539/4708/5683/10383/5694/4717/5693/509/6390/126328/292/4718/4716/5879/4715/54205/4726/9167/1327/6392/4729/6391/516/84790/522/293/3312/1345/10376/4709/4710/1349/7979/29796/1340/4711/4697/1337/5688/4695/4725/517/27089/10975/518/291/7381/7388/5880/1350/1351/1347/514/4707/4701
hsa00190 4722/515/533/9296/374291/9550/54539/51382/4696/7385/4714/4698/51079/4728/1537/506/10476/4694/4712/4731/7386/513/55967/4702/4700/4706/10063/1329/9377/4713/539/4708/4717/509/6390/126328/4718/4716/4715/54205/4726/9167/1327/6392/4729/6391/516/9551/522/1345/521/4709/4710/1349/29796/1340/4711/4697/1337/4695/4725/517/27089/10975/518/7381/7388/10632/1350/1351/1347/514/1353/4707/4701